const SAVE="scrollingStrollingRPG";
const INITIAL={level:1,xp:0,hp:40,maxHp:40,attack:8,defense:3,speed:10};
const SCHOOLS={
 Iron:{tag:"IRON",motto:"If you cannot be moved, you cannot be defeated.",stats:{defense:2,maxHp:5},techniques:["Iron Guard","Rooted Stance","Iron Heart","Retaliation"]},
 "Falling Leaf":{tag:"FALLING LEAF",motto:"The strongest strike is the one that never meets resistance.",stats:{speed:2},techniques:["Quick Step","Flowing Strike","Afterimage","Empty Space"]},
 Crimson:{tag:"CRIMSON",motto:"One perfect strike is worth a thousand ordinary ones.",stats:{attack:2},techniques:["Keen Edge","Blood Rush","Killing Stroke","Execution"]},
 "Empty Hand":{tag:"EMPTY HAND",motto:"A weapon does not make the warrior.",stats:{attack:1,defense:1},techniques:["Disarm","Iron Fist","Adaptive Form","No Blade"]},
 Silent:{tag:"SILENT",motto:"The battle that never happens is the greatest victory.",stats:{speed:1,defense:1},techniques:["Quiet Step","Read Intent","Unseen Blade","Empty Battle"]}
};
const ROUTES={
 "Mountain Road":{label:"MOUNTAIN ROAD",desc:"An abandoned dojo is said to lie beyond the ridge.",specials:["martial","shrine","teacher"]},
 "City Road":{label:"CITY ROAD",desc:"The growing industrial city lies beyond the valley.",specials:["industrial","merchant","combat"]},
 "Battlefield Road":{label:"BATTLEFIELD ROAD",desc:"Old scars still mark the road where the war was decided.",specials:["veteran","memory","combat"]},
 "Temple Road":{label:"TEMPLE ROAD",desc:"A quiet temple road winds toward the hills.",specials:["temple","shrine","teacher"]}
};
const enemies=[
 {name:"Road Bandit",hp:22,attack:6,defense:2,speed:7,xp:2,model:"🥷"},
 {name:"Wandering Ronin",hp:28,attack:7,defense:3,speed:11,xp:3,model:"⚔️"},
 {name:"Mountain Thug",hp:35,attack:9,defense:4,speed:5,xp:4,model:"👹"},
 {name:"Rifleman",hp:25,attack:11,defense:2,speed:8,xp:4,model:"🎯"},
 {name:"Veteran Duelist",hp:42,attack:10,defense:5,speed:9,xp:6,model:"⚔️"}
];
let player={...INITIAL,primary:null,secondary:null,mastery:{},techniques:[],reputation:{Industrialists:0,Traditionalists:0,Temples:0,"Common People":0},route:"City Road",steps:0,unspentLevels:0};
let battle=null,transitioning=false,journeyToken=0;
const $=id=>document.getElementById(id);
function save(){localStorage.setItem(SAVE,JSON.stringify(player));}
function load(){const raw=localStorage.getItem(SAVE);if(!raw)return;try{player=Object.assign({...INITIAL,primary:null,secondary:null,mastery:{},techniques:[],reputation:{Industrialists:0,Traditionalists:0,Temples:0,"Common People":0},route:"City Road",steps:0,unspentLevels:0},JSON.parse(raw));player.unspentLevels=Number(player.unspentLevels||0);}catch(_){localStorage.removeItem(SAVE);}}
function clearStage(){const scene=$("combat-scene"),pc=$("player-stage"),enemy=$("enemy-stage");scene.classList.remove("walking","arrived");pc.classList.remove("approaching","stage-attacking");enemy.classList.remove("objective-arrival","stage-attacking");$("stage-enemy-model").textContent="";$("stage-enemy-name").textContent="";["stage-enemy-hp","stage-enemy-stam","stage-enemy-tech"].forEach(id=>$(id).style.width="0%");}
function resetGame(){journeyToken++;transitioning=false;if(battle)battle.running=false;battle=null;localStorage.clear();player={...INITIAL,primary:null,secondary:null,mastery:{},techniques:[],reputation:{Industrialists:0,Traditionalists:0,Temples:0,"Common People":0},route:"City Road",steps:0,unspentLevels:0};clearStage();closeMenu();closeLevelUp();updateStats(false);beginJourney(true);}
function updateStats(persist=true){const ids={level:"level",hp:"hp",attack:"attack",defense:"defense",speed:"speed",xp:"xp"};Object.entries(ids).forEach(([k,id])=>{if($(id))$(id).textContent=k==="hp"?`${Math.max(0,player.hp)}/${player.maxHp}`:player[k];});$("level-card").textContent=player.level;$("menu-level").textContent=player.level;$("main-hpbar").style.width=`${Math.max(0,player.hp/player.maxHp*100)}%`;const need=player.level*10;$("xpbar").style.width=`${Math.min(100,player.xp/need*100)}%`;if($("xp-needed"))$("xp-needed").textContent=need;$("primary-school").textContent=player.primary?player.primary.toUpperCase():"UNTRAINED";$("active-technique").textContent=player.techniques.length?player.techniques[player.techniques.length-1].toUpperCase():"NONE";$("current-route").textContent=(ROUTES[player.route]||ROUTES["City Road"]).label;$("menu-school").textContent=player.primary||"Untrained";$("menu-mastery").textContent=player.primary?(player.mastery[player.primary]||"Novice"):"Novice";updateStageBars();if(persist)save();}
function updateStageBars(){if(!$("stage-player-stam"))return;$("stage-player-stam").style.width=`${battle?battle.playerMeter:0}%`;$("stage-enemy-stam").style.width=`${battle?battle.enemyMeter:0}%`;$("stage-player-tech").style.width=`${battle?battle.playerTech:0}%`;$("stage-enemy-tech").style.width=`${battle?battle.enemyTech:0}%`;}
function openMenu(){if(battle&&battle.running)return;$("menu-overlay").classList.add("open");$("menu-overlay").setAttribute("aria-hidden","false");}
function closeMenu(){$("menu-overlay").classList.remove("open");$("menu-overlay").setAttribute("aria-hidden","true");}
function buttons(list){$("choices").innerHTML="";list.forEach(item=>{const b=document.createElement("button");b.textContent=item.text;b.onclick=item.action;$("choices").appendChild(b);});}
function setScene(mode,enemy=null){$("stage-mode").textContent=mode;$("stage-player-hp").style.width=`${Math.max(0,player.hp/player.maxHp*100)}%`;if(enemy){$("stage-enemy-model").textContent=enemy.model;$("stage-enemy-name").textContent=enemy.name.toUpperCase();$("stage-enemy-hp").style.width=`${Math.max(0,enemy.hp/enemy.maxHp*100)}%`;}else clearStage();updateStageBars();}
function showTravelState(){setScene("TRAVELING");$("mode").textContent="TRAVELING";$("event-title").textContent="The Road Continues";$("event-text").textContent=`You walk steadily onward along the ${ROUTES[player.route].label.toLowerCase()}.`;$("choices").innerHTML="";updateStats(false);}
function teacherEncounter(){return {type:"choice",title:"A Quiet Teacher",text:"An old swordsman watches your stance. He offers a single lesson before returning to his meditation.",choices:[{text:"Ask about motion",school:"Falling Leaf",result:"He corrects your footing. You feel the road differently."},{text:"Ask about the blade",school:"Crimson",result:"He shows you how little movement a perfect strike requires."},{text:"Ask about stillness",school:"Silent",result:"He teaches you to read intent before the body moves."},{text:"Ask about endurance",school:"Iron",result:"He teaches you to receive force without surrendering ground."},{text:"Ask about the empty hand",school:"Empty Hand",result:"He teaches you to let the weapon become unnecessary."}]};}
function combatEncounter(){return {type:"combat",title:"A Stranger Blocks the Road",text:"Steel catches the light. Your opponent waits for you to make the first mistake.",enemy:enemies[Math.floor(Math.random()*enemies.length)]};}
function chooseEncounter(){
 player.steps++;
 if(!player.primary && player.steps>=7)return teacherEncounter();
 if(Math.random()<0.70)return combatEncounter();
 if(Math.random()<0.03)return {type:"crossroad"};
 const route=ROUTES[player.route]||ROUTES["City Road"];
 const nonCombat=route.specials.filter(k=>k!=="combat");
 const kind=nonCombat[Math.floor(Math.random()*nonCombat.length)];
 if(kind==="teacher")return teacherEncounter();
 if(kind==="martial")return {type:"choice",title:"Ruined Dojo",text:"An abandoned dojo stands beneath the trees. Someone has left a school scroll beside the door.",choices:[{text:"Study the Falling Leaf scroll",school:"Falling Leaf",result:"The old diagrams teach you to let force pass through empty space."},{text:"Study the Iron scroll",school:"Iron",result:"The old diagrams teach you to become the stone beneath the blow."}]};
 if(kind==="shrine")return {type:"choice",title:"A Wayside Shrine",text:"A weathered shrine rests beside the road. Incense burns despite the empty path.",choices:[{text:"Offer a prayer",effect:{hp:player.maxHp},rep:{Temples:2},result:"The quiet gives you strength. Your wounds close."},{text:"Leave a coin and continue",effect:{speed:1},rep:{"Common People":1},result:"A small act of respect changes how you carry yourself."}]};
 if(kind==="industrial")return {type:"choice",title:"The Iron Age",text:"A machine wagon rattles past. Its driver looks at your sword and laughs.",choices:[{text:"Watch the machine",rep:{Industrialists:2},result:"You study the new world instead of dismissing it."},{text:"Ignore the machine",rep:{Traditionalists:1},school:"Iron",result:"You keep walking. Your grip tightens around the old way."}]};
 if(kind==="merchant")return {type:"choice",title:"A Merchant Wagon",text:"A merchant has stopped to repair a wheel and offers you a moment of conversation.",choices:[{text:"Help repair the wheel",effect:{defense:1},rep:{"Common People":2},result:"Practical work leaves you stronger and earns a little trust."},{text:"Ask about the road ahead",effect:{speed:1},result:"The merchant points you toward a faster route."}]};
 if(kind==="veteran")return {type:"choice",title:"Old Soldier",text:"A scarred veteran sits beside a milestone. He recognizes something in the way you walk.",choices:[{text:"Sit with him",rep:{Traditionalists:2},result:"You share the silence of people who remember the war."},{text:"Ask what he remembers",rep:{"Common People":1},school:"Silent",result:"His answer reminds you that surviving a battle is not the same as winning it."}]};
 if(kind==="memory")return {type:"choice",title:"The Old Battlefield",text:"Broken stone and rusted metal lie beneath the grass. Something about the place feels familiar.",choices:[{text:"Search the ruins",effect:{attack:2},rep:{Traditionalists:1},result:"You find a familiar mark among the wreckage. Your hand closes around the sword."},{text:"Leave it undisturbed",school:"Silent",rep:{"Common People":1},result:"Some memories do not need to be disturbed to teach you."}]};
 if(kind==="temple")return {type:"choice",title:"Temple Bells",text:"A distant bell marks the hour. A monk tends the path ahead.",choices:[{text:"Listen",rep:{Temples:2},result:"The rhythm settles your breathing."},{text:"Ask about the old schools",school:"Silent",rep:{Temples:1},result:"The monk reminds you that a tradition can survive in the mind even when its buildings disappear."}]};
 return {type:"choice",title:"A Long Road",text:"The road is quiet. For once, there is nothing demanding your attention.",choices:[{text:"Practice your stance",school:"Falling Leaf",result:"A few steps become a hundred. Practice becomes habit."},{text:"Rest beneath a tree",effect:{hp:player.maxHp},result:"You rest until the ache leaves your muscles."}]};
}
function beginJourney(force=false){if(transitioning&&!force)return;const token=++journeyToken;transitioning=true;const e=chooseEncounter(),scene=$("combat-scene"),pc=$("player-stage"),target=$("enemy-stage");clearStage();showTravelState();scene.classList.remove("walking","arrived");void scene.offsetWidth;scene.classList.add("walking");pc.classList.add("approaching");setTimeout(()=>{if(token!==journeyToken)return;scene.classList.remove("walking");pc.classList.remove("approaching");scene.classList.add("arrived");setTimeout(()=>{if(token!==journeyToken)return;scene.classList.remove("arrived");transitioning=false;target.classList.add("objective-arrival");if(e.type==="combat"){setScene("ENCOUNTER",e.enemy);$("mode").textContent="ENCOUNTER";$("event-title").textContent=e.title;$("event-text").textContent=e.text;setTimeout(()=>{if(token===journeyToken)startBattle(e.enemy);},450);}else if(e.type==="crossroad"){showCrossroad();}else{setScene("ENCOUNTER");$("stage-enemy-model").textContent="?";$("stage-enemy-name").textContent="THE ROAD AHEAD";showEncounter(e);}},300);},1150);}
function nextEncounter(){if(battle&&battle.running)return;transitioning=false;battle=null;showTravelState();beginJourney(true);}
function showCrossroad(){const choices=Object.entries(ROUTES).filter(([name])=>name!==player.route).sort(()=>Math.random()-.5).slice(0,2);$("stage-mode").textContent="CROSSROADS";$("mode").textContent="THE ROAD DIVIDES";$("event-title").textContent="Choose Your Road";$("event-text").textContent="Two roads stretch ahead. Where will you take your training?";buttons(choices.map(([name,r])=>({text:`${r.label} — ${r.desc}`,action:()=>{player.route=name;updateStats();nextEncounter();}})));}
function showEncounter(e){$("mode").textContent="ENCOUNTER";$("event-title").textContent=e.title;$("event-text").textContent=e.text;buttons(e.choices.map(c=>({text:c.text,action:()=>resolveChoice(c)})));}
function resolveChoice(c){if(c.school)learnSchool(c.school);Object.entries(c.effect||{}).forEach(([k,v])=>{if(k==="hp")player.hp=player.maxHp;else player[k]+=v;});Object.entries(c.rep||{}).forEach(([k,v])=>player.reputation[k]=(player.reputation[k]||0)+v);updateStats();$("mode").textContent="RESULT";$("event-title").textContent=c.school?`${c.school} lesson`:(c.result?"The Road Teaches":"Choice made");$("event-text").textContent=c.result||"Your choice changes the journey.";buttons([{text:"Continue walking",action:nextEncounter}]);}
function learnSchool(name){const school=SCHOOLS[name];if(!school)return;if(!player.primary){player.primary=name;player.mastery[name]="Novice";}else if(player.primary!==name&&!player.secondary){player.secondary=name;player.mastery[name]="Novice";}const isNew=!player.techniques.includes(school.techniques[0]);Object.entries(school.stats).forEach(([k,v])=>{if(k==="maxHp"){player.maxHp+=v;player.hp+=v;}else player[k]+=v;});if(isNew)player.techniques.push(school.techniques[0]);if(player.primary===name&&player.mastery[name]==="Novice"&&player.techniques.length>=3)player.mastery[name]="Student";}
function startBattle(template){if(!template)return;clearStage();battle={enemy:{...template,maxHp:template.hp},playerMeter:0,enemyMeter:0,playerTech:0,enemyTech:0,lastTime:performance.now(),running:true};$("mode").textContent="RESOLVING COMBAT";$("event-title").textContent="Combat is resolving...";$("event-text").textContent=player.techniques.length?`${player.techniques[player.techniques.length-1]} is readying as you fight.`:"Your actions are automatic. Watch the battle above.";$("choices").innerHTML="";setScene("COMBAT",battle.enemy);requestAnimationFrame(combatLoop);}
function damage(a,d){let value=Math.max(1,a.attack-d.defense+Math.floor(Math.random()*3));if(a===player&&player.primary==="Crimson"&&Math.random()<.16)value*=2;if(a===player&&player.primary==="Falling Leaf"&&player.speed>d.speed)value+=Math.ceil((player.speed-d.speed)/2);return value;}
function combatLoop(now){if(!battle||!battle.running)return;const dt=Math.min(.05,(now-battle.lastTime)/1000);battle.lastTime=now;battle.playerMeter=Math.min(100,battle.playerMeter+dt*player.speed*4);battle.enemyMeter=Math.min(100,battle.enemyMeter+dt*battle.enemy.speed*4);battle.playerTech=Math.min(100,battle.playerTech+dt*(5+(player.speed*.15)));battle.enemyTech=Math.min(100,battle.enemyTech+dt*4);if(battle.playerMeter>=100||battle.enemyMeter>=100){if(battle.playerMeter>=100&&battle.enemyMeter>=100){if(player.speed>=battle.enemy.speed)doPlayerAttack();else doEnemyAttack();}else if(battle.playerMeter>=100)doPlayerAttack();else doEnemyAttack();if(!battle||!battle.running)return;}if(battle&&battle.playerTech>=100)doTechnique();if(battle&&battle.enemyTech>=100)battle.enemyTech=0;updateCombatBars();updateStageBars();requestAnimationFrame(combatLoop);}
function doPlayerAttack(){battle.playerMeter=0;const d=damage(player,battle.enemy);battle.enemy.hp-=d;animateAttack("player");floatDamage("enemy",d);updateCombatBars();updateStageBars();if(battle.enemy.hp<=0)victory();}
function doEnemyAttack(){battle.enemyMeter=0;const d=damage(battle.enemy,player);player.hp-=d;animateAttack("enemy");floatDamage("player",d);updateStats();updateCombatBars();updateStageBars();if(player.hp<=0)defeat();}
function doTechnique(){if(!battle)return;battle.playerTech=0;const school=player.primary||"Iron";let multiplier=1.55;if(school==="Crimson")multiplier=2.15;if(school==="Iron")multiplier=1.7;if(school==="Falling Leaf")multiplier=1.6;if(school==="Empty Hand")multiplier=1.5;if(school==="Silent")multiplier=1.35;let d=Math.max(2,Math.floor(damage(player,battle.enemy)*multiplier));if(school==="Silent"&&Math.random()<.35){battle.playerMeter=Math.min(100,battle.playerMeter+35);$("event-text").textContent="Unseen Blade turns an opening into momentum.";}battle.enemy.hp-=d;animateTechnique();floatDamage("enemy",d);updateCombatBars();if(battle.enemy.hp<=0)victory();}
function updateCombatBars(){if(!battle)return;const e=battle.enemy;$("stage-player-hp").style.width=`${Math.max(0,player.hp/player.maxHp*100)}%`;$("stage-enemy-hp").style.width=`${Math.max(0,e.hp/e.maxHp*100)}%`;}
function animateAttack(side){const el=document.querySelector(`.${side}-stage`);if(!el)return;el.classList.remove("stage-attacking");void el.offsetWidth;el.classList.add("stage-attacking");setTimeout(()=>el.classList.remove("stage-attacking"),350);}
function animateTechnique(){const el=$("player-stage");el.classList.remove("stage-technique");void el.offsetWidth;el.classList.add("stage-technique");setTimeout(()=>el.classList.remove("stage-technique"),600);}
function floatDamage(side,d){const el=document.querySelector(`.${side}-stage`);if(!el)return;const n=document.createElement("span");n.className="stage-damage";n.textContent=`-${d}`;el.appendChild(n);setTimeout(()=>n.remove(),800);}
function victory(){if(!battle)return;const defeated=battle.enemy;battle.running=false;const gained=defeated.xp;player.xp+=gained;player.reputation["Common People"]=(player.reputation["Common People"]||0)+1;levelCheck();updateStats();$("mode").textContent="VICTORY";$("event-title").textContent=`${defeated.name} defeated`;$("event-text").textContent=`Victory. You gain ${gained} XP.`;setScene("VICTORY");buttons([{text:"Continue walking",action:nextEncounter}]);battle=null;updateStageBars();}
function defeat(){if(battle)battle.running=false;battle=null;$("mode").textContent="DEFEAT";$("event-title").textContent="The Journey Ends";$("event-text").textContent="Your strength gives out on the road.";buttons([{text:"Begin a new journey",action:resetGame}]);setScene("DEFEAT");updateStageBars();}
function levelCheck(){while(player.xp>=player.level*10){player.xp-=player.level*10;player.level++;player.unspentLevels+=2;}if(player.unspentLevels>0)showLevelUp();}
function showLevelUp(){if(battle)battle.running=false;$("level-up-overlay").classList.add("open");$("level-up-overlay").setAttribute("aria-hidden","false");renderLevelUp();}
function closeLevelUp(){if($("level-up-overlay")){$("level-up-overlay").classList.remove("open");$("level-up-overlay").setAttribute("aria-hidden","true");}}
function renderLevelUp(){if(!$("level-up-points"))return;$("level-up-points").textContent=player.unspentLevels;$("level-up-level").textContent=player.level;["maxHp","attack","defense","speed"].forEach(k=>{const el=$("alloc-"+k);if(el)el.textContent=player[k];});}
function allocateStat(stat){if(!player.unspentLevels)return;const gains={maxHp:5,attack:1,defense:1,speed:1};player[stat]+=gains[stat];if(stat==="maxHp")player.hp+=gains[stat];player.unspentLevels--;renderLevelUp();updateStats();if(player.unspentLevels<=0){closeLevelUp();$("mode").textContent="TRAINING";$("event-title").textContent="Your path takes shape";$("event-text").textContent=`You are now level ${player.level}. Your improvements are your own.`;buttons([{text:"Continue walking",action:nextEncounter}]);}}
function init(){try{$("top-menu").onclick=openMenu;$("menu-nav").onclick=openMenu;$("close-menu").onclick=closeMenu;$("reset-game").onclick=()=>{if(confirm("Reset the entire game? This clears all saved progress and active game state."))resetGame();};$("menu-overlay").onclick=e=>{if(e.target.id==="menu-overlay")closeMenu();};$("character-nav").onclick=()=>{openMenu();$("event-text").textContent=`${player.primary||"Untrained"} • ${player.techniques.length} technique${player.techniques.length===1?"":"s"}.`;};$("skills-nav").onclick=()=>{openMenu();$("event-text").textContent=player.techniques.length?`Techniques: ${player.techniques.join(", ")}.` : "Your martial training has not yet begun.";};$("alloc-maxHp").onclick=()=>allocateStat("maxHp");$("alloc-attack").onclick=()=>allocateStat("attack");$("alloc-defense").onclick=()=>allocateStat("defense");$("alloc-speed").onclick=()=>allocateStat("speed");load();updateStats();showTravelState();beginJourney(true);}catch(error){console.error("Game initialization failed:",error);$("event-title").textContent="Game failed to initialize";$("event-text").textContent="Please reload the page.";}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();